openapi: 3.0.3
info:
  title: Exordos Core v1 Status API
  version: latest
  description: OpenAPI - Exordos Core v1
components:
  responses:
    Error:
      description: Error response.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      title: error
      description: Error occurred while processing request
      type: object
      required:
        - status
        - json
      properties:
        status:
          type: integer
          description: The HTTP status code
          minimum: 400
          exclusiveMaximum: true
          example: 503
        json:
          type: object
          description: Detail error map
          required:
            - code
            - type
            - message
          properties:
            code:
              type: integer
              description: The HTTP status code
              minimum: 400
              exclusiveMaximum: true
              example: 503
            type:
              type: string
              description: Error class name
              example: OSError
            message:
              type: string
              description: Error message
              example: A human-readable explanation of problem
      example:
        code: 400
        json:
          code: 400
          type: ValidationErrorException
          message: Validation error occurred.
    UniversalAgent_Get:
      type: object
      properties:
        uuid:
          type: string
          example: 00000000-0000-0000-0000-000000000000
          format: uuid
        name:
          type: string
          minLength: 0
          maxLength: 255
          example: any_string
        description:
          type: string
          minLength: 0
          maxLength: 255
          example: any_string
          default: ''
        created_at:
          type: string
          x-ogen-time-format: '2006-01-02T15:04:05.000576Z'
          example: '2006-01-02T15:04:05.000576Z'
          format: date-time
          default: '2006-01-02T15:04:05.000576Z'
        updated_at:
          type: string
          x-ogen-time-format: '2006-01-02T15:04:05.000576Z'
          example: '2006-01-02T15:04:05.000576Z'
          format: date-time
          default: '2006-01-02T15:04:05.000576Z'
        capabilities:
          type: object
          additionalProperties:
            oneOf:
              - type: string
              - type: integer
              - type: boolean
              - type: object
              - type: array
                items: {}
          example:
            key: value
          default: {}
        facts:
          type: object
          additionalProperties:
            oneOf:
              - type: string
              - type: integer
              - type: boolean
              - type: object
              - type: array
                items: {}
          example:
            key: value
          default: {}
        node:
          type: string
          example: 00000000-0000-0000-0000-000000000000
          format: uuid
        status:
          type: string
          enum:
            - ACTIVE
            - DISABLED
            - ERROR
            - NEW
          example: NEW
          default: NEW
      required:
        - uuid
        - name
        - node
    UniversalAgent_Create:
      type: object
      properties:
        uuid:
          type: string
          example: 00000000-0000-0000-0000-000000000000
          format: uuid
        name:
          type: string
          minLength: 0
          maxLength: 255
          example: any_string
        description:
          type: string
          minLength: 0
          maxLength: 255
          example: any_string
          default: ''
        created_at:
          type: string
          x-ogen-time-format: '2006-01-02T15:04:05.000576Z'
          example: '2006-01-02T15:04:05.000576Z'
          format: date-time
          default: '2006-01-02T15:04:05.000576Z'
        updated_at:
          type: string
          x-ogen-time-format: '2006-01-02T15:04:05.000576Z'
          example: '2006-01-02T15:04:05.000576Z'
          format: date-time
          default: '2006-01-02T15:04:05.000576Z'
        capabilities:
          type: object
          additionalProperties:
            oneOf:
              - type: string
              - type: integer
              - type: boolean
              - type: object
              - type: array
                items: {}
          example:
            key: value
          default: {}
        facts:
          type: object
          additionalProperties:
            oneOf:
              - type: string
              - type: integer
              - type: boolean
              - type: object
              - type: array
                items: {}
          example:
            key: value
          default: {}
        node:
          type: string
          example: 00000000-0000-0000-0000-000000000000
          format: uuid
        status:
          type: string
          enum:
            - ACTIVE
            - DISABLED
            - ERROR
            - NEW
          example: NEW
          default: NEW
      required:
        - uuid
        - name
        - node
    UniversalAgent_Update:
      type: object
      properties:
        uuid:
          type: string
          example: 00000000-0000-0000-0000-000000000000
          format: uuid
        name:
          type: string
          minLength: 0
          maxLength: 255
          example: any_string
        description:
          type: string
          minLength: 0
          maxLength: 255
          example: any_string
          default: ''
        created_at:
          type: string
          x-ogen-time-format: '2006-01-02T15:04:05.000576Z'
          example: '2006-01-02T15:04:05.000576Z'
          format: date-time
          default: '2006-01-02T15:04:05.000576Z'
        updated_at:
          type: string
          x-ogen-time-format: '2006-01-02T15:04:05.000576Z'
          example: '2006-01-02T15:04:05.000576Z'
          format: date-time
          default: '2006-01-02T15:04:05.000576Z'
        capabilities:
          type: object
          additionalProperties:
            oneOf:
              - type: string
              - type: integer
              - type: boolean
              - type: object
              - type: array
                items: {}
          example:
            key: value
          default: {}
        facts:
          type: object
          additionalProperties:
            oneOf:
              - type: string
              - type: integer
              - type: boolean
              - type: object
              - type: array
                items: {}
          example:
            key: value
          default: {}
        node:
          type: string
          example: 00000000-0000-0000-0000-000000000000
          format: uuid
        status:
          type: string
          enum:
            - ACTIVE
            - DISABLED
            - ERROR
            - NEW
          example: NEW
          default: NEW
      required:
        - uuid
        - name
        - node
    KindModel_Filter:
      type: object
      properties:
        kind:
          type: string
          minLength: 0
          maxLength: 64
          example: any_string
      required:
        - kind
    KindModel_Get:
      type: object
      properties:
        kind:
          type: string
          minLength: 0
          maxLength: 64
          example: any_string
      required:
        - kind
    Resource_Get:
      type: object
      properties:
        created_at:
          type: string
          x-ogen-time-format: '2006-01-02T15:04:05.000576Z'
          example: '2006-01-02T15:04:05.000576Z'
          format: date-time
          default: '2006-01-02T15:04:05.000576Z'
        updated_at:
          type: string
          x-ogen-time-format: '2006-01-02T15:04:05.000576Z'
          example: '2006-01-02T15:04:05.000576Z'
          format: date-time
          default: '2006-01-02T15:04:05.000576Z'
        uuid:
          type: string
          example: 00000000-0000-0000-0000-000000000000
          format: uuid
        kind:
          type: string
        value:
          type: object
          additionalProperties:
            oneOf:
              - type: string
              - type: integer
              - type: boolean
              - type: object
              - type: array
                items: {}
          example:
            key: value
        hash:
          type: string
          minLength: 0
          maxLength: 256
          example: any_string
          default: ''
        full_hash:
          type: string
          minLength: 0
          maxLength: 256
          example: any_string
          default: ''
        status:
          type: string
          minLength: 0
          maxLength: 32
          example: any_string
          default: ACTIVE
        node:
          type: string
          example: 00000000-0000-0000-0000-000000000000
          format: uuid
          nullable: true
        res_uuid:
          type: string
          example: 00000000-0000-0000-0000-000000000000
          format: uuid
      required:
        - kind
    Resource_Create:
      type: object
      properties:
        created_at:
          type: string
          x-ogen-time-format: '2006-01-02T15:04:05.000576Z'
          example: '2006-01-02T15:04:05.000576Z'
          format: date-time
          default: '2006-01-02T15:04:05.000576Z'
        updated_at:
          type: string
          x-ogen-time-format: '2006-01-02T15:04:05.000576Z'
          example: '2006-01-02T15:04:05.000576Z'
          format: date-time
          default: '2006-01-02T15:04:05.000576Z'
        uuid:
          type: string
          example: 00000000-0000-0000-0000-000000000000
          format: uuid
        kind:
          type: string
        value:
          type: object
          additionalProperties:
            oneOf:
              - type: string
              - type: integer
              - type: boolean
              - type: object
              - type: array
                items: {}
          example:
            key: value
        hash:
          type: string
          minLength: 0
          maxLength: 256
          example: any_string
          default: ''
        full_hash:
          type: string
          minLength: 0
          maxLength: 256
          example: any_string
          default: ''
        status:
          type: string
          minLength: 0
          maxLength: 32
          example: any_string
          default: ACTIVE
        node:
          type: string
          example: 00000000-0000-0000-0000-000000000000
          format: uuid
          nullable: true
        res_uuid:
          type: string
          example: 00000000-0000-0000-0000-000000000000
          format: uuid
      required:
        - kind
    Resource_Update:
      type: object
      properties:
        created_at:
          type: string
          x-ogen-time-format: '2006-01-02T15:04:05.000576Z'
          example: '2006-01-02T15:04:05.000576Z'
          format: date-time
          default: '2006-01-02T15:04:05.000576Z'
        updated_at:
          type: string
          x-ogen-time-format: '2006-01-02T15:04:05.000576Z'
          example: '2006-01-02T15:04:05.000576Z'
          format: date-time
          default: '2006-01-02T15:04:05.000576Z'
        uuid:
          type: string
          example: 00000000-0000-0000-0000-000000000000
          format: uuid
        kind:
          type: string
        value:
          type: object
          additionalProperties:
            oneOf:
              - type: string
              - type: integer
              - type: boolean
              - type: object
              - type: array
                items: {}
          example:
            key: value
        hash:
          type: string
          minLength: 0
          maxLength: 256
          example: any_string
          default: ''
        full_hash:
          type: string
          minLength: 0
          maxLength: 256
          example: any_string
          default: ''
        status:
          type: string
          minLength: 0
          maxLength: 32
          example: any_string
          default: ACTIVE
        node:
          type: string
          example: 00000000-0000-0000-0000-000000000000
          format: uuid
          nullable: true
        res_uuid:
          type: string
          example: 00000000-0000-0000-0000-000000000000
          format: uuid
      required:
        - kind
  parameters:
    UniversalAgentUuid:
      name: UniversalAgentUuid
      in: path
      schema:
        type: string
        example: 00000000-0000-0000-0000-000000000000
        format: uuid
      required: true
    name:
      name: name
      in: query
      schema:
        type: string
        minLength: 0
        maxLength: 255
        example: any_string
    description:
      name: description
      in: query
      schema:
        type: string
        minLength: 0
        maxLength: 255
        example: any_string
        default: ''
    created_at:
      name: created_at
      in: query
      schema:
        type: string
        x-ogen-time-format: '2006-01-02T15:04:05.000576Z'
        example: '2006-01-02T15:04:05.000576Z'
        format: date-time
        default: '2006-01-02T15:04:05.000576Z'
    updated_at:
      name: updated_at
      in: query
      schema:
        type: string
        x-ogen-time-format: '2006-01-02T15:04:05.000576Z'
        example: '2006-01-02T15:04:05.000576Z'
        format: date-time
        default: '2006-01-02T15:04:05.000576Z'
    capabilities:
      name: capabilities
      in: query
      schema:
        type: object
        additionalProperties:
          oneOf:
            - type: string
            - type: integer
            - type: boolean
            - type: object
            - type: array
              items: {}
        example:
          key: value
        default: {}
    facts:
      name: facts
      in: query
      schema:
        type: object
        additionalProperties:
          oneOf:
            - type: string
            - type: integer
            - type: boolean
            - type: object
            - type: array
              items: {}
        example:
          key: value
        default: {}
    node:
      name: node
      in: query
      schema:
        type: string
        example: 00000000-0000-0000-0000-000000000000
        format: uuid
        nullable: true
    status:
      name: status
      in: query
      schema:
        type: string
        minLength: 0
        maxLength: 32
        example: any_string
        default: ACTIVE
    KindModelKind:
      name: KindModelKind
      in: path
      schema:
        type: string
        minLength: 0
        maxLength: 64
        example: any_string
      required: true
    uuid:
      name: uuid
      in: query
      schema:
        type: string
        example: 00000000-0000-0000-0000-000000000000
        format: uuid
    kind:
      name: kind
      in: query
      schema:
        type: string
    value:
      name: value
      in: query
      schema:
        type: object
        additionalProperties:
          oneOf:
            - type: string
            - type: integer
            - type: boolean
            - type: object
            - type: array
              items: {}
        example:
          key: value
    hash:
      name: hash
      in: query
      schema:
        type: string
        minLength: 0
        maxLength: 256
        example: any_string
        default: ''
    full_hash:
      name: full_hash
      in: query
      schema:
        type: string
        minLength: 0
        maxLength: 256
        example: any_string
        default: ''
    ResourceRes_uuid:
      name: ResourceRes_uuid
      in: path
      schema:
        type: string
        example: 00000000-0000-0000-0000-000000000000
        format: uuid
      required: true
paths:
  /:
    get:
      summary: Base application url
      responses:
        '200':
          description: Get nested urls
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          $ref: '#/components/responses/Error'
      operationId: Get_urls
  /specifications/:
    get:
      summary: Get OpenApiSpecificationRoute OpenApiSpecificationControllers
      tags: []
      parameters: []
      responses:
        '200':
          description: Get nested urls
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          $ref: '#/components/responses/Error'
      operationId: Filter_specifications
  /specifications/3.0.3:
    get:
      summary: OpenApi specification
      tags: []
      parameters: []
      responses:
        '200':
          description: OpenApi specification
          content:
            application/json:
              schema:
                type: object
                properties: {}
        default:
          $ref: '#/components/responses/Error'
      operationId: Get_OpenApi_specification
  /v1/:
    get:
      summary: Returns a list of all routes in the main route that are 
        collection
      tags: []
      parameters:
        - name: filters
          description: "the filters to apply when filtering the routes (Is not\nimplemented
            now)\n"
          schema:
            type: string
          in: query
        - name: order_by
          description: "fields to order the routes by (Is not implemented\nnow)\n"
          schema:
            type: string
          in: query
      responses:
        '200':
          description: Get nested urls
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          $ref: '#/components/responses/Error'
      operationId: Filter_v1
  /v1/agents/:
    post:
      summary: Create UniversalAgent
      tags:
        - UniversalAgent
      parameters: []
      responses:
        '201':
          description: UniversalAgent_Create
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UniversalAgent_Create'
        default:
          $ref: '#/components/responses/Error'
      operationId: Create_v1_agents
      requestBody:
        description: UniversalAgent_Create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UniversalAgent_Create'
  /v1/agents/{UniversalAgentUuid}:
    get:
      summary: Get UniversalAgent
      tags:
        - UniversalAgent
      parameters:
        - name: UniversalAgentUuid
          in: path
          schema:
            type: string
            example: 00000000-0000-0000-0000-000000000000
            format: uuid
          required: true
      responses:
        '200':
          description: UniversalAgent_Get
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UniversalAgent_Get'
        default:
          $ref: '#/components/responses/Error'
      operationId: Get_v1_agents_UniversalAgentUuid
    put:
      summary: Update UniversalAgent
      tags:
        - UniversalAgent
      parameters:
        - name: UniversalAgentUuid
          in: path
          schema:
            type: string
            example: 00000000-0000-0000-0000-000000000000
            format: uuid
          required: true
      responses:
        '200':
          description: UniversalAgent_Update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UniversalAgent_Update'
        default:
          $ref: '#/components/responses/Error'
      operationId: Update_v1_agents_UniversalAgentUuid
      requestBody:
        description: UniversalAgent_Update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UniversalAgent_Update'
    delete:
      summary: Delete UniversalAgent
      tags:
        - UniversalAgent
      parameters:
        - name: UniversalAgentUuid
          in: path
          schema:
            type: string
            example: 00000000-0000-0000-0000-000000000000
            format: uuid
          required: true
      responses:
        '204':
          description: UniversalAgent_Delete
        default:
          $ref: '#/components/responses/Error'
      operationId: Delete_v1_agents_UniversalAgentUuid
  /v1/kind/:
    get:
      summary: Get KindModels
      tags:
        - KindModel
      parameters:
        - name: kind
          in: query
          schema:
            type: string
      responses:
        '200':
          description: KindModel_Filter
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/KindModel_Filter'
        default:
          $ref: '#/components/responses/Error'
      operationId: Filter_v1_kind
  /v1/kind/{KindModelKind}:
    get:
      summary: Get KindModel
      tags:
        - KindModel
      parameters:
        - name: KindModelKind
          in: path
          schema:
            type: string
            minLength: 0
            maxLength: 64
            example: any_string
          required: true
      responses:
        '200':
          description: KindModel_Get
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KindModel_Get'
        default:
          $ref: '#/components/responses/Error'
      operationId: Get_v1_kind_KindModelKind
  /v1/kind/{KindModelKind}/resources/:
    post:
      summary: Create Resource
      tags:
        - Resource
      parameters:
        - name: KindModelKind
          in: path
          schema:
            type: string
            minLength: 0
            maxLength: 64
            example: any_string
          required: true
      responses:
        '201':
          description: Resource_Create
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource_Create'
        default:
          $ref: '#/components/responses/Error'
      operationId: Create_v1_kind_KindModelKind_resources
      requestBody:
        description: Resource_Create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource_Create'
  /v1/kind/{KindModelKind}/resources/{ResourceRes_uuid}:
    get:
      summary: Get Resource
      tags:
        - Resource
      parameters:
        - name: KindModelKind
          in: path
          schema:
            type: string
            minLength: 0
            maxLength: 64
            example: any_string
          required: true
        - name: ResourceRes_uuid
          in: path
          schema:
            type: string
            example: 00000000-0000-0000-0000-000000000000
            format: uuid
          required: true
      responses:
        '200':
          description: Resource_Get
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource_Get'
        default:
          $ref: '#/components/responses/Error'
      operationId: Get_v1_kind_KindModelKind_resources_ResourceRes_uuid
    put:
      summary: Update Resource
      tags:
        - Resource
      parameters:
        - name: KindModelKind
          in: path
          schema:
            type: string
            minLength: 0
            maxLength: 64
            example: any_string
          required: true
        - name: ResourceRes_uuid
          in: path
          schema:
            type: string
            example: 00000000-0000-0000-0000-000000000000
            format: uuid
          required: true
      responses:
        '200':
          description: Resource_Update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource_Update'
        default:
          $ref: '#/components/responses/Error'
      operationId: Update_v1_kind_KindModelKind_resources_ResourceRes_uuid
      requestBody:
        description: Resource_Update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource_Update'
    delete:
      summary: Delete Resource
      tags:
        - Resource
      parameters:
        - name: KindModelKind
          in: path
          schema:
            type: string
            minLength: 0
            maxLength: 64
            example: any_string
          required: true
        - name: ResourceRes_uuid
          in: path
          schema:
            type: string
            example: 00000000-0000-0000-0000-000000000000
            format: uuid
          required: true
      responses:
        '204':
          description: Resource_Delete
        default:
          $ref: '#/components/responses/Error'
      operationId: Delete_v1_kind_KindModelKind_resources_ResourceRes_uuid
servers:
  - url: http://127.0.0.1:11012
    description: ''
    variables:
      version:
        enum:
          - v1
        default: v1
tags:
  - name: UniversalAgent
    description: ''
  - name: Resource
    description: ''
  - name: KindModel
    description: ''
